export { default as EyeIcon } from './eye.svg';
export { default as LogoIcon } from './logo.svg';
export { default as JobsIcon } from './jobs.svg';
export { default as OverviewIcon } from './overview.svg';
export { default as ProfileIcon } from './profile.svg';
export { default as TasksIcon } from './tasks.svg';
export { default as PlusIcon } from './plus.svg';
export { default as ArrowDownIcon } from './arrow-down.svg';
export { default as CrossIcon } from './cross.svg';
