import { type Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Loader } from '~/shared/ui/components/components';
import { GlobalLoaderProvider } from './providers/loader-provider/index';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <ToastContainer />
                <GlobalLoaderProvider>
                    {children}
                    <Loader />
                </GlobalLoaderProvider>
            </body>
        </html>
    );
}

export { metadata };
export default RootLayout;
